Add Delete Funtionality
obcode/glabs pull request #21
Opened 2022-01-27 17:19 UTC by fritterhoff

Hello @obcode,

Depending on the size of the course and the number of assignments, a considerable number of repositories can be created. As a counterpart to creating the repos, now the delete function at the end of the semester. :)

2022-01-31 12:50 UTC, mgudemann requested changes
Sieht ok aus, ich bin aber kein Go/Glabs Experte.
Ich fände es gut, wenn die Funktionen noch dkoumentiert wären, z.B. mit dem Format der Namen Projekte die gelöscht werden.

2022-01-31 12:50 UTC, mgudemann commented on gitlab/delete.go
> +		fmt.Printf("it is only possible to generate for students oder groups, not for %v", per)
Die Message kommt mir nicht ganz richtig vor. Das "oder" ist deutsch und es geht ja um löschen

2022-01-31 12:50 UTC, mgudemann commented on gitlab/delete.go
> +				log.Error().Str("project", name).Msg("deleting project failed")
hier vielleicht noch den Namen des Projekts mit dazu, wenn das löschen nicht funktioniert hat?

2022-01-31 13:01 UTC, fritterhoff commented on gitlab/delete.go
> +		fmt.Printf("it is only possible to generate for students oder groups, not for %v", per)
Ups. Copy & paste ...

2022-02-21 08:09 UTC, merged

2022-02-21 08:09 UTC, obcode commented
Thanks for this one!